name: Build

on:
  push:

jobs:
  build:
    name: Build
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - "windows-2022"
        dotnet-version:
          - "net8.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build
      run: |
        dotnet build -f ${{ matrix.dotnet-version }} --no-restore

 